version: "3.8"
# name: sdb
services:
  # agent:
  #   image: portainer/agent
  #   environment:
  #     AGENT_CLUSTER_ADDR: tasks.agent
  #     CAP_HOST_MANAGEMENT: 1
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /var/lib/docker/volumes:/var/lib/docker/volumes
  #     - /:/host
  #   ports:
  #     - target: 9001
  #       published: 9001
  #       protocol: tcp
  #       mode: host
  #   networks:
  #     - portainer_agent
  #   deploy:
  #     mode: global
  #     placement:
  #       constraints: [node.platform.os == linux]


  web:
    entrypoint:
    - sleep
    - infinity
    image: docker/dev-environments-default:stable-1
    init: true
    volumes:
    - type: volume
      source: volume-docker-sock
      target: /var/run/docker.sock
      
  yubi:
    command:
    - infinity
    entrypoint:
    - sleep
    image: docker/dev-environments-default:stable-1
    #build: docker build https://github.com/kindtek/yubico-net-sdk.git#develop:/Yubico.NativeShims/docker/Ubuntu
    init: true
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: sdb
    networks:
      default: null
    stop_signal: SIGKILL
    volumes:
    - type: volume
      source: volume-sdb-sol
      target: /usr/bin
    - type: volume
      source: volume-docker-sock
      target: /var/run/docker.sock
    - type: volume
      source: volume-sdb-dev
      target: /com.docker.devenvironments.code
    - type: volume
      source: volume-sdb-dev-app
      target: /home/vscode
  py:
    command:
    - infinity
    entrypoint:
    - sleep
    image: python
    init: true
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: sdb
    networks:
      default: null
    stop_signal: SIGKILL
    volumes:
    - type: volume
      source: volume-sdb-sol
      target: /usr/bin
    - type: volume
      source: volume-docker-sock
      target: /var/run/docker.sock
    - type: volume
      source: volume-sdb-dev
      target: /com.docker.devenvironments.code
    - type: volume
      source: volume-sdb-dev-app
      target: /home/vscode
  sol:
    command:
    - "apt-get update -qq && apt-get install -yq wget"
    entrypoint:
    - "/usr/bin/solana-run.sh"
    image: solanalabs/solana:stable
    ports:
    - "8899:8899"
    init: true
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: sdb
    networks:
      default: null
    stop_signal: SIGKILL
    volumes:
    - type: volume
      source: volume-sdb-sol
      target: /usr/bin
    - type: volume
      source: volume-docker-sock
      target: /var/run/docker.sock
    - type: volume
      source: volume-sdb-dev
      target: /com.docker.devenvironments.code
    - type: volume
      source: volume-sdb-dev-app
      target: /home/vscode
  app:
    depends_on:
    - "sol"
    - "yubi"
#    - "agent"
    command:
    - infinity
    entrypoint:
    - sleep
    image: docker/dev-environments-default:stable-1
    init: true
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: sdb
    networks:
      default: null
    stop_signal: SIGKILL
    volumes:
    - type: volume
      source: volume-sdb-sol
      target: /usr/bin
    - type: volume
      source: volume-docker-sock
      target: /var/run/docker.sock
    - type: volume
      source: volume-sdb-dev
      target: /com.docker.devenvironments.code
    - type: volume
      source: volume-sdb-dev-app
      target: /home/vscode
networks:
  default:
    name: default-net
    attachable: true
  # portainer_agent:
  #   driver: overlay
  #   attachable: true

volumes:
  volume-sdb-dev:
    name: volume-sdb-dev
    #external: true
  volume-sdb-dev-app:
    name: volume-sdb-dev-app
    #external: true
  volume-sdb-sol:
    name: volume-sdb-sol
    #external: true
  volume-docker-sock:
    name: volume-docker-sock
    #external: true