version: "3.8"
services:
  sol:
    image: solanalabs/solana:v1.14.8
    ports:
      - "8899:8899"
    init: true
    networks:
      default: null
    stop_signal: SIGKILL
    volumes:
      - volume-sdb-bin:/usr/bin
  app:
    image: docker/dev-environments-default:stable-1
    init: true
    networks:
      default: null
    stop_signal: SIGKILL
    volumes:
      - volume-sdb-bin:/usr/local/bin
volumes:
  volume-sdb-bin:
