name: yubico-net-sdk-objective_jemison
services:
  app:
    command:
    - infinity
    depends_on:
     - "py"
     - "sol"
     - "yubi"
  
    entrypoint:
    - sleep
    image: docker/dev-environments-default:stable-1
    init: true
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: yubico-net-sdk-objective_jemison
    networks:
      default: null
    stop_signal: SIGKILL
    volumes:
    - type: volume
      source: volume-sdb-sol
      target: /usr/bin
    - type: volume
      source: volume-sdb-py
      target: /usr/bin
    - type: volume
      source: volume-docker-sock
      target: /var/run/docker.sock
    - type: volume
      source: volume-sdb-dev
      target: /com.docker.devenvironments.code
    - type: volume
      source: volume-sdb-vscode
      target: /home/vscode
  py:
    command:
    - infinity
    entrypoint:
    - sleep
    image: python
    init: true
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: yubico-net-sdk-objective_jemison
    networks:
      default: null
    stop_signal: SIGKILL
    volumes:
    - type: volume
      source: volume-sdb-py
      target: /usr/bin
  sol:
    command:
    - apt-get update -q && apt-get install -y wget
    entrypoint:
    - /usr/bin/solana-run.sh
    image: solanalabs/solana:stable
    init: true
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: yubico-net-sdk-objective_jemison
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8899
      published: "8899"
      protocol: tcp
    stop_signal: SIGKILL
    volumes:
    - type: volume
      source: volume-sdb-sol
      target: /usr/bin
  web:
    command:
    - infinity
    entrypoint:
    - sleep
    image: docker/dev-environments-default:stable-1
    init: true
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: yubico-net-sdk-objective_jemison
    networks:
      default: null
    stop_signal: SIGKILL
    volumes:
    - type: volume
      source: volume-docker-sock
      target: /var/run/docker.sock
    - type: volume
      source: volume-yubico-net-sdk-objective_jemison
      target: /com.docker.devenvironments.code
    - type: volume
      source: vsCodeServerVolume-yubico-net-sdk-objective_jemison-web
      target: /home/vscode
  yubi:
    command:
    - infinity
    entrypoint:
    - sleep
    image: docker/dev-environments-default:stable-1
    init: true
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: yubico-net-sdk-objective_jemison
    networks:
      default: null
    stop_signal: SIGKILL
    volumes:
    - type: volume
      source: volume-sdb-sol
      target: /usr/bin
    - type: volume
      source: volume-docker-sock
      target: /var/run/docker.sock
    - type: volume
      source: volume-sdb-dev
      target: /com.docker.devenvironments.code
    - type: volume
      source: volume-sdb-vscode
      target: /home/vscode
networks:
  default:
    name: default-net
    attachable: true
volumes:
  volume-docker-sock:
    name: volume-docker-sock
  volume-sdb-dev:
    name: volume-sdb-dev
  volume-sdb-py:
    name: volume-sdb-py
  volume-sdb-sol:
    name: volume-sdb-sol
  volume-sdb-vscode:
    name: volume-sdb-vscode
  volume-yubico-net-sdk-objective_jemison:
    name: volume-yubico-net-sdk-objective_jemison
    external: true
  vsCodeServerVolume-yubico-net-sdk-objective_jemison-web:
    name: vsCodeServerVolume-yubico-net-sdk-objective_jemison-web
