version: "3.8"
# name: sdb
services:
  # agent:
  #   image: portainer/agent
  #   environment:
  #     AGENT_CLUSTER_ADDR: tasks.agent
  #     CAP_HOST_MANAGEMENT: 1
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /var/lib/docker/volumes:/var/lib/docker/volumes
  #     - /:/host
  #   ports:
  #     - target: 9001
  #       published: 9001
  #       protocol: tcp
  #       mode: host
  #   networks:
  #     - portainer_agent
  #   deploy:
  #     mode: global
  #     placement:
  #       constraints: [node.platform.os == linux]


  web:
    entrypoint:
    - sleep
    - infinity
    image: docker/dev-environments-default:stable-1
    init: true
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.container.name: sdb

    # ports:
    # - "8080:8080"
    volumes:
    - type: volume
      source: volume-sdb-web
      target: /usr/bin
    - type: volume
      source: volume-docker-sock-web
      target: /var/run/docker.sock
    
  yubi:
    command:
    - infinity
    entrypoint:
    - sleep
    image: docker/dev-environments-default:stable-1
    #build: docker build https://github.com/kindtek/yubico-net-sdk.git#develop:/Yubico.NativeShims/docker/Ubuntu
    init: true
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: sdb
    networks:
      default: null
    stop_signal: SIGKILL
    volumes:
    - type: volume
      source: volume-sdb-yubi
      target: /usr/bin
    - type: volume
      source: volume-docker-sock-yubi
      target: /var/run/docker.sock

  py:
    command:
    - infinity
    entrypoint:
    - sleep
    image: python
    init: true
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: sdb
    networks:
      default: null
    stop_signal: SIGKILL
    volumes:
    - type: volume
      source: volume-sdb-py
      target: /usr/bin
    - type: volume
      source: volume-docker-sock-py
      target: /var/run/docker.sock

  sol:
    command:
    - "apt-get update -q && apt-get install -y wget"
    entrypoint:
    - "/usr/bin/solana-run.sh"
    image: solanalabs/solana:stable
    ports:
    - "8899:8899"
    init: true
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: sdb
    networks:
      default: null
    stop_signal: SIGKILL
    volumes:
    - type: volume
      source: volume-sdb-sol
      target: /usr/bin
    - type: volume
      source: volume-docker-sock-sol
      target: /var/run/docker.sock

  app:
    depends_on:
    - "sol"
    - "yubi"
    - "py"
    command:
    - infinity
    entrypoint:
    - sleep
    # command:
    # - "apt-get upgrade" #" && apt-get install -y python3-venv python3-pip pcscd swig libpcsclite1 python-pycparser && ln -s /usr/bin/python3 /usr/bin/python && ln -s /usr/bin/pip3 /usr/bin/pip"
    image: docker/dev-environments-default:stable-1
    init: true
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: sdb
    networks:
      default: null
    stop_signal: SIGKILL
    volumes:
    - type: volume
      source: volume-sdb-app
      target: /usr/bin
    - type: volume
      source: volume-docker-sock-app
      target: /var/run/docker.sock

networks:
  default:
    name: default-net
    attachable: true
  # portainer_agent:
  #   driver: overlay
  #   attachable: true

volumes:
  volume-docker-sock-app:
    name: volume-docker-sock-app
  volume-docker-sock-web:
    name: volume-docker-sock-web
  volume-docker-sock-py:
    name: volume-docker-sock-py
  volume-docker-sock-yubi:
    name: volume-docker-sock-yubi
  volume-docker-sock-sol:
    name: volume-docker-sock-sol
  volume-sdb-app:
    name: volume-sdb-app
  volume-sdb-web:
    name: volume-sdb-web
  volume-sdb-py:
    name: volume-sdb-py
  volume-sdb-yubi:
    name: volume-sdb-yubi
  volume-sdb-sol:
    name: volume-sdb-sol
  
  


