version: "3.8"

services:
  yubi:
    env_file:
      - ../../sdb.env
      - ../../yub.env
    build:
      args:
        USER_ID: 1000
        GROUP_ID: 1000
        ARTIFACT_DIR: ubuntu-x64
      context: .
      dockerfile: docker/Ubuntu/Dockerfile
    # TODO - MAKE IMAGE NAME DYNAMIC
    image: kindtek/yubico-safedb-ubuntu
