version: "3.8"

services:
  yubi:
    env_file:
      - ../../sdb.env
      - ../../yub.env
    build:
      args:
        - YUBICO_USER_ID=1000 
        - YUBICO_GROUP_ID=1000
        - YUBICO_BUILD=$YUBICO_BUILD
        - YUBICO_BUILD_ENV=$YUBICO_BUILD_ENV
        - YUBICO_BUILD_ENV_VERSION=$YUBICO_BUILD_ENV_VERSION
        - YUBICO_BUILD_ENV_NAME=$YUBICO_BUILD_ENV_NAME
        - SDB_YUB_DOCKER_IMG=$SDB_YUB_DOCKER_IMG
        - SDB_YUB_DOCKER_TAG=$SDB_YUB_DOCKER_TAG
        # - SDB_YUB_DOCKER_TAG_ARM64=$SDB_YUB_DOCKER_TAG_ARM64
        # - SDB_YUB_DOCKER_TAG_X64=$SDB_YUB_DOCKER_TAG_X64
        # - SDB_YUB_DOCKER_TAG_X86=$SDB_YUB_DOCKER_TAG_X86
        - SDB_YUB_DOCKER="${SDB_YUB_DOCKER_IMG}:${SDB_YUB_DOCKER_TAG}"
        - YUBICO_ARTIFACT_DIR=$YUBICO_ARTIFACT_DIR
      context: .
      dockerfile: docker/Ubuntu/Dockerfile
    # TODO - MAKE IMAGE NAME DYNAMIC
    image: kindtek/yubico-safedb-ubuntu
