version: "3.8"

services:
  yubi:
    env_file:
      - ../../sdb.env
      - ../sdb.env
    build:
      args:
        - USER_ID=`id -u`
        - GROUP_ID=`id -g`
        - YUBICO_BUILD=${YUBICO_BUILD}
        - YUBICO_BUILD_ENV=${YUBICO_BUILD_ENV}
        - YUBICO_BUILD_ENV_VERSION=${YUBICO_BUILD_ENV_VERSION}
        - YUBICO_BUILD_ENV_NAME=${YUBICO_BUILD_ENV_NAME}
        - SDB_YUB_DOCKER_IMG="kindtek/yubico-sdb-${YUBICO_BUILD_ENV}"
        - SDB_YUB_DOCKER_TAG=$YUBICO_BUILD-$SAFEDB_VERSION-${YUBICO_BUILD_ENV_NAME}
        - SDB_YUB_DOCKER="${SDB_YUB_DOCKER_IMG}:${SDB_YUB_DOCKER_TAG}"
        - YUBICO_ARTIFACT_DIR="${YUBICO_BUILD_ENV}-$(dpkg --print-architecture)"
      context: .
      dockerfile: docker/Ubuntu/Dockerfile
    # TODO - MAKE IMAGE NAME DYNAMIC
    image: kindtek/yubico-sdb-ubuntu
